server:
  port: 1102

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/dcom_api?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: duyky123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

# App Properties
duykypaul:
  app:
    jwtSecret: kyLCSecretKey
    jwtExpirationMs: 3600000
